### ISSUE TITLE
Reddit Replacement

### ISSUE THREAD

**Issue by acerix** [demcra/demcra#1]
https://www.reddit.com/r/RedditAlternatives/comments/3bzvod/nonprofit_wikipedialike_democratized_reddit/csrf9k5

**Comment by drew-y** [comment]
We should establish some goals:
1. The site will be free and open source
2. The organization will be non-profit funded to avoid the alienation the monetization process inevitably leads to
3. The site will be democratic with an amendable constitution outlining the process
4. It should probably have a more modern (but familiar) interface
5. This site will be funded in non intrusive ways (donations, merchandise etc)

We should definitely try and recruit board members and schedule meetings. Every other week sounds good to me.

**Comment by drew-y** [comment]
We should also work to find a name that everyone in the community agrees on. I personally do like demcra but we should be certain that everyone else does too.

**Comment by acerix** [comment]
I drafted a constitution as a starting point, with an open source clause (and some humour...):

https://github.com/demcra/demcra/blob/master/documents/constitution.md

Regarding the interface, I'm a fan of bootstrap (what's on demcra.com) but am open to suggestions.  

I'm not really attached the the name "demcra", but it's useful to have some working name for the project until we have more people to make that decision. It's easy to change that later, right now I'm looking more at functionality vs "branding".

The board should decide on which ways to be funded, but I want to stay away from ads too.  Some other ideas: membership fee from voting members? percentage of bitcoin/dogecoin tips?

As a minimum, we should try to get 5 board members with at least 3 at every meeting as a quorum for voting (ie. over 50%).

Seeing how this is a global organization, might not be so easy to coordinate meetings, but just to throw something out there; how about every second Saturday at 8 PM UTC?

**Comment by drew-y** [comment]
I like the constitution so far! My only concern is the MIT license. While I personally think that the MIT license is great, I think it might be better to start off with AGPL to help us grow.

> Regarding the interface, I'm a fan of bootstrap (what's on demcra.com) but am open to suggestions.

I've been using bootstrap for awhile now and enjoy it also, but recently I've also discovered semantic-ui which I've been using to create the [seaddit](https://github.com/drew-y/seaddit) prototype and I think I might be starting to prefer it.

> percentage of bitcoin/dogecoin tips

I was thinking this would be a good idea too.

> membership fee from voting members?

This could hurt our potential ability to grow, I don't think I would have joined reddit if I had to pay to vote. That being said maybe a membership fee for creating subreddits? Or we could provide a "sustaining member" flair for users that pay. Something like that would be cool. We could also just beg for donations like wikipedia does.

> Saturday at 8 PM UTC

Sounds good to me

**Comment by acerix** [comment]
Just to clarify, everyone will be able to participate for free, by "voting members" I mean those eligible to elect board members.  It would be good to require a nominal fee of say $5 per year, which helps prove their identity so someone can't vote twice, but also would be a reliable source of funds given thousands of members.

Thanks for the suggestions.  I consider MIT to be the least restrictive license of it's kind, and as I understand, the main difference with GPL is that any derivatives would also need to also be GPL which I don't think we need to worry about. But I don't know these licenses that well, so let me know if I'm missing something, I'm not opposed to AGPL if that is more suitable.

**Comment by drew-y** [comment]
> by "voting members" I mean those eligible to elect board members

That makes way more sense. I like it.

I really do love the MIT license but for our case, at least in the short term, I think AGPL is more suitable. It means that any derivative work must also be open source which can help us grow the platform. I'd recommend going to MIT after we've got a strong footing.

**Comment by acerix** [comment]
I added the AGPL to the constitution, I don't see any reason not to allow both licenses.

But seeing how the GPL is supposed to prevent someone from reusing our code in a closed-source project, if someone were to do just that, I doubt we'd even find out about it, let alone have any legal recourse, so I still don't see the benefit for us to use it.

**Comment by acerix** [comment]
Cleaning up this "place holder" issue, please 21

**Comment by acerix** [comment]
Cleaning up this "place holder" issue, please add a new issue to contribute.
