### ISSUE TITLE
Formatting on submitted links.

### ISSUE THREAD

**Issue by AlexPoulsen** [demcra/demcra#12]
Any submitted links should use a title 1-6 instead of usual body formatting.
Or each realm should be able to format it individually.
Maybe a separation between the text and link.
Semi-unrelated, but pictures, gifs, videos, etc could be shown at the top (choice at time of submission or editing)

**Comment by acerix** [comment]
Link formatting is fixed now.

I'm moving the preview idea to a new issue. It would be a nice feature, but will take some time, so I'll come back to it.
