### ISSUE TITLE
New submissions that are not upvoted at all are shown at the very bottom of the main page. 

### ISSUE THREAD

**Issue by AlexPoulsen** [demcra/demcra#13]
New submissions that are not upvoted at all are shown at the very bottom of the main page.
I think this is how the popularity is calculated.
Simple fix: auto uproot your own posts, comments.

**Comment by acerix** [comment]
Good call, votes added automatically after posting now.
I'll leave this open as I intend to improve the popularity calculations soon, was looking at these:
http://amix.dk/blog/post/19588  for topics
http://www.redditblog.com/2009/10/reddits-new-comment-sorting-system.html for comments

**Comment by AlexPoulsen** [comment]
Good, I read both.
I think there should be a way to temporarily block a certain topic. As in:
"Block anything related to:___ Dogs _______"
in this case you would now see mostly just cats if this was in a realm like /r/aww
(edited my lack of knowledge about markdown)

**Comment by AlexPoulsen** [comment]
I seem to be able to edit your posts...

**Comment by acerix** [comment]
I can also edit yours, I guess it's for moderating.  At first, I thought you meant on demcra, which was a bit worrisome because it's not allowed there.

For blocking topics, I think that can be part of the keyword search (not available yet).  For example, searching for "cats" would only find cats, but searching for "-cats" would exclude all cats.

**Comment by AlexPoulsen** [comment]
I like it!
Also, "no nsfw" and "no violence" toggles would be useful too.
As well as a permanent block option, like searching for -cats but always activated.
After 2 or 3 searches of -cats, an option to perma-block cats would pop up (not as a pop-up, but in the same window)
