### ISSUE TITLE
Remaining features for Prototype

### ISSUE THREAD

**Issue by acerix** [demcra/demcra#2]

**Comment by acerix** [comment]
Join and Login features are done, time to reserve your username!

**Comment by acerix** [comment]
User and Realm URLs are working now.  If you try to access a realm that doesn't exist, there's a quick link to create it.

**Comment by acerix** [comment]
Update the homepage with a demo interface and topic links are working

**Comment by acerix** [comment]
New features:
Submit topic
Topic image thumbnail is generated automatically
Subscribe/unsub to realms

**Comment by polsvoice** [comment]
I think it would also be cool to let users have avatars.

**Comment by acerix** [comment]
Great idea, thanks! I put it down for the beta

https://github.com/demcra/demcra/issues/6

Do you like the way github does it? That's what I have in mind

**Comment by acerix** [comment]
New features:
comment post and voting - basic functionality, but layout needs work
qr code generator - used to deposit cryptocurrency, examples on donate page

**Comment by AlexPoulsen** [comment]
You should have the comment fill-in field appear below the comment. Either that or as a "pop-up". Quotes since it would be in the same window. Maybe a transparent overlay above the comments with a "Your comment is here" sort of text or graphic in the location the comment will be posted.
Also a cancel button.

**Comment by acerix** [comment]
For comments, I plan to put the comment box inline like you mentioned, I should have that done tomorrow.  The way it works now will be the fallback for someone without javascript.

I uploaded the site images so they can be updated here then I'll pull to the live site.

**Comment by acerix** [comment]
Comment box is now inline and  layout improved a bit.

**Comment by AlexPoulsen** [comment]
Is comment editing added yet?

**Comment by acerix** [comment]
Edit/delete for comments is in now.

**Comment by acerix** [comment]
Edit/delete for topic summary is in.

**Comment by acerix** [comment]
By default, topics are now sorted by "popularity", currently defined as:
    (vote_score + comment_count) / (1 + seconds_since_posted)

**Comment by acerix** [comment]
Sorting is in
Calling the prototype done, will add leftover features I wanted as new issues
