### ISSUE TITLE
Internal server error problem

### ISSUE THREAD

**Issue by Adam24** [demcra/demcra#23]
Our server is having issues. Any ETA on when the server will be back online?

**Comment by acerix** [comment]
Thanks for notifying me.  It's working again after I freed up some space and restarted the database.  It wasn't actually out of space, there's some issue with the disk quotas, so I'll check that out tonight.  

By the way, the whole site is running from a $7/month VPS, so it's not very robust at this point.

**Comment by Adam24** [comment]
Actually @acerix, the threads trigger the flaming server error but the front page doesn't anymore.

**Comment by acerix** [comment]
I freed up some more space so it should be good for now.  It probably just needs a reboot as there is actually 20 GB free, but I'll wait until I'm done work (in 5 hours) in case anything goes wrong.

**Comment by acerix** [comment]
Quota issue is fixed after reboot
