### ISSUE TITLE
Cryptocurrency Integration

### ISSUE THREAD

**Issue by acerix** [demcra/demcra#3]
Users can deposit Bitcoin or Dogecoin, then attach arbitrary amounts when posting a comment, which is deposited to the account of the user they are replying to.  Users can also do this without leaving a comment, so the tip is anonymous.  Each topic and comment shows how much has been tipped.

**Comment by AlexPoulsen** [comment]
I think users should be able to also give a little to pay for server hosting, url registration, etc.

**Comment by acerix** [comment]
Are you saying we should accept donations via BTC or DOGE? Absolutely! I will make a page for that now.

My personal server can handle probably less than 1000 users at once, but I can't really afford to pay for a real server out of my pocket, so the sooner we get some cash flow, the better!

**Comment by acerix** [comment]
For the record, these are the initial donation addresses I created:

BTC: 1Jbn3srZhjuA7tP6odncgqAUNc3b2BbZjb
LTC: LM3xGMXeTVc3XdWpNDHsrvaYwkfxgET8N9
DOGE: D8sVK1dQtAjUpq2WD5o35HDaLkzX6Swghk

We will need to discuss a better way to secure these wallets though, so that the board has easy access to the funds, but individual members do not, and also keep it far away from thieves (cold).  To be clear, the addresses will have to be regenerated at that time, so even I don't have access to the new ones.

**Comment by AlexPoulsen** [comment]
I think we should look into making Demcra a Public Benefit Corporation once we get it going.
[Public Benefit Corporation](https://en.wikipedia.org/wiki/Public-benefit_corporation)
[http://benefitcorp.net](http://benefitcorp.net)
[ello.co is a pbc](https://ello.co/wtf/about/pbc/)

**Comment by acerix** [comment]
That sounds good to me. I've been thinking some kind of non-profit but haven't really looked at the options.
I'm in Canada, so for me personally to do the registration, I'm sure it would be easier to form a Canadian entity. But it's more important to consider which country/entity will provide the best protection for our users/organization in the long term.
This is something the board needs to come to a consensus on sooner rather than later. I propose that we move this forward as soon as we have 5 members.

**Comment by AlexPoulsen** [comment]
<img width="128" alt="demcra gold" src="https://cloud.githubusercontent.com/assets/9259671/8611644/6e1ea09c-2692-11e5-874c-f785c125e67e.png"><img width="128" alt="demcra silver" src="https://cloud.githubusercontent.com/assets/9259671/8611645/72e6391e-2692-11e5-942d-8d9d9b3bcc62.png">
I have vector versions too
So Demcra Gold is actual money (through cryptocurrency) given to the receiver. Wouldn't be too common, reserved for really good posts.
Democrat Silver is a "currency" rewarded for any donations. All merchandise gives an equal value and all direct donations give double value. Likely will be used more than gold.
Everyone's user page shows gold/silver received, bought, and given.

**Comment by acerix** [comment]
Cool icons!  At first, it looks a bit like a Dogecoin, but I think it is distinct enough that it will not be mistaken.  

Instead of using both "real" points (currency) and some kind of "fake" points (eg. reddit Gold) though,  I think it would be better just to stick with the currency option.  We could give donors 100 DOGE (about 2 cents) to get started, for example, or maybe 1% the value of their donation.  It will be possible to tip trivial amounts too, maybe even as low as 0.00000001 DOGE. 

Maybe a topic with less than $5 worth of tips would get a silver icon, then gold for $5+.

**Comment by acerix** [comment]
I starting adding support for BTC, LTC and DOGE, check out the Wallet section. Currently, it's only possible to deposit coins, more coming soon!

**Comment by acerix** [comment]
Added the ability to include a tip when replying.  Withdrawals are next!

**Comment by acerix** [comment]
Rather than showing the amount of tips for each currency (even with 3 currency, that's way too many numbers to display!)  they are converted to their value in DOGE at the time of the tip, so they tip value roughly equals the same amount in DOGE.  (Or exactly, if all tips were in DOGE and/or the exchange rates did not fluctuate).  Of course, the value of the tip itself stays the same and is not converted to DOGE. 

Thoughts on using silver for less than 50000 DOGE and gold for 50000+ DOGE?  (roughly $10)  
I have a feeling the logos above will need some help to scale to such a tiny size, but will see what I can do.

**Comment by acerix** [comment]
The icons are in now, and withdrawals are working!
